### PR TITLE
Stop using npm workspaces

### PR DESCRIPTION
**Pull request by Pezmc**
## Description

Stops using npm workspaces, in favour updating the existing script to run `npm install` inside each package manually.

The initial install time is slightly slower, but the speed is comparable after that.

As part of #20 

## Related Issue(s)

#20 

## Checklist

 - [x] I have read the [contribution guidelines](https://github.com/flowforge/flowforge/blob/main/CONTRIBUTING.md)
 - [x] Suitable unit/system level tests have been added and they pass 
 - [-] Documentation has been updated
    - [ ] Upgrade instructions
    - [ ] Configuration details
    - [ ] Concepts
 - [ ] Changes `flowforge.yml`?
    - [ ] Issue/PR raised on `flowforge/helm` to update ConfigMap Template
    - [ ] Issue/PR raised on `flowforge/CloudProject` to update values for Staging/Production

## Labels

 - [ ] Backport needed? -> add the `backport` label
 - [ ] Includes a DB migration? -> add the `area:migration` label

### CODE REVIEW

**Comment by joepavitt** [comment]
Just tried pulling this to run, and can no longer run `npm run serve` on /flowforge due to `sh: npm-run-all: command not found`

**Comment by Pezmc** [comment]
@joepavitt That doesn't seem like it'll be related. Perhaps caused by the package-lock chages. Are you sure npm install had completed?

**Comment by Pezmc** [comment]
I'd like a guinea pig to run though this with on Monday morning, any volunteers @joepavitt @Steve-Mcl @hardillb?

**Comment by joepavitt** [comment]
> Are you sure npm install had completed?

It definitely had. 

> Any volunteers?

Fine to do walkthrough, but don't work Mondays.

**Comment by Steve-Mcl** [comment]
> I'd like a guinea pig to run though this with on Monday morning, any volunteers @joepavitt @Steve-Mcl @hardillb?

I'm happy to sit in / participate as required @Pezmc 

##### some thoughts that merit discussion?
* include vscode settings (we mostly, if not all use vscode but even if a member is _not_ using vscode, they would simply be ignored)
* include custom spellings (shared dictionary for inclusion of things like `flowforge`)
* eslint settings (e.g. adding vue to checked files)
* there are more: but my brain has stopped working

**Comment by Pezmc** [comment]
This PR is sitting until our next release, please see #20 for information

**Review by knolleary — APPROVED** [review]
Having pulled this branch, run `npm install && npm run init` my workspace appears to be in a good state.
 - No longer npm workspace driven
 - Each package repo has its own node_modules
 - All necessary Symlinks appear to be in place

Great job!

**Pull request merged**
